[package]
name = "community_bank"
version = "0.1.0"
edition = "2018"

[dependencies]
near-sdk = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
